# Site settings
title: Barcelona Free Software - Meetup
email: barcelona-free-software@kde-espana.org
description: > # this means to ignore newlines until "baseurl:"
    The Barcelona Free Software meetup is an open space
    for coders and users who love free software that has +600 members.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bcnfs.github.io" # the base hostname & protocol for your site
twitter_username: bcnfs
github_username:  bcnfs

# Build settings
markdown: kramdown
