# Site settings
title: Barcelona Free Software
email: barcelona-free-software@bcnfs.org
description: We are a community of Free and Open Source software creators in Barcelona. On our main activities is our meetup group, an open gathering for developers and users who share a love for free software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bcnfs.org/" # the base hostname & protocol for your site
twitter_username: BCNFreeSoftware
fosstodon_username: BCNFreeSoftware
github_username:  bcnfs
meetup_username: Barcelona-Free-Software

# Build settings
markdown: kramdown
